### ISSUE TITLE
[suggestion] Proposal to OCA

### ISSUE THREAD

**Issue by alejandrosantana** [lbaldi/it#10]
Hi.
I haven't tried yet, but looks quite complete. Have you thought about proposing to include it into OCA repositories?

**Comment by lbaldi** [comment]
I Did It. in fact they contacted me and we exchanged some emails , but were asking requirements such as membership and other things.

**Comment by alejandrosantana** [comment]
Oh, yes, the new CLA. OK, anyway, an interesting module.
