### ISSUE TITLE
Question: Application 's versioning?

### ISSUE THREAD

**Issue by ygol** [lbaldi/it#5]
Hello Leandro,

I started using/testing your IT module. How do you handle versioning of application?

cusotmer 1's server use application 1 version 1.0
customer 2's server use application 2 version 2.0

Tnx.

**Comment by lbaldi** [comment]
Using differents version for each branch.
7.0 branch is 2.0 . 
8.0 branch is 1.0 ( version restarted bc migration)

**Comment by ygol** [comment]
I wasn't clear enough. sorry. 
I meant that in different servers instances, I use different application's version. 
in the snapshot I use version 1.16.04 of solusvm but for another customer I could use an older verision like 1.15.00.

![image](https://cloud.githubusercontent.com/assets/2945174/4989669/8fef80b8-6984-11e4-9b37-4ab7c94c6b40.png)

thank you

**Comment by lbaldi** [comment]
You should create two application registries one for each version. Each version has a link, a manual, etc.

**Comment by ygol** [comment]
got it. thank you
