### ISSUE TITLE
Error on Equipments' duplication

### ISSUE THREAD

**Issue by ygol** [lbaldi/it#6]
Duplication button doesn't work because of a Constraint Error: PIN must be unique!

Solution: overwrite copy function with other pin value.

**Comment by ygol** [comment]
Not too sure about how to go about this but here's what I did:
1. I forked the repository
2. I modified the code
3. I created a pull request in the forked repository

can you use this to update the code?

**Comment by lbaldi** [comment]
Thanks you for reporting this bug. Thats the way, i can update the code from your pull.

**Comment by lbaldi** [comment]
Fixed.
