### ISSUE TITLE
Partner link in "Equipment" does not list existing partners

### ISSUE THREAD

**Issue by andreassantoro** [lbaldi/it#9]
If you create a new equipment, the field "Partner" which is required creates all the time the same partner. The field seam to be unable to list already created partners.
- Odoo 8.0
- Ubuntu LTS 14.04
- English

**Comment by lbaldi** [comment]
The list only show partners who have "Manage IT" checked. Search for it after "Active" on partner settings.

**Comment by andreassantoro** [comment]
Thank you, It works as you described.
Very helpful module, thank you!
